export enum RoleEnum {
  PATIENT = "PATIENT",
  ADMIN_CLINIC = "ADMIN_CLINIC",
  ADMIN_CLINIC_LAB = "ADMIN_CLINIC_LAB",
  CLINIC_VALIDATOR = "CLINIC_VALIDATOR",
  THIRD_PARTY = "THIRD_PARTY",
  SUPER_ADMIN = "SUPER_ADMIN",
  SUPER_ADMIN_EXECUTIVE = "SUPER_ADMIN_EXECUTIVE",
  SUPER_ADMIN_OPS = "SUPER_ADMIN_OPS",
  SUPER_ADMIN_INVESTOR = "SUPER_ADMIN_INVESTOR",
  ADMIN_VFS = "ADMIN_VFS",
}
